name: "Update plugins"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Runs weekly on monday at 00:00

jobs:
  update-plugins:
    name: Update plugins
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Update plugins
        id: update
        run: |
          echo "Updating plugins.json plugins..."
          output=$(nix run --quiet nixpkgs#npins -- --lock-file plugins.json update --full 2>&1)
          {
            echo "output<<EOF"
            echo -e "$output"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          assignees: sonntag
          body: |
            ## Plugin updates

            ```
            ${{ steps.update.outputs.output }}
            ```
          branch: update-plugins
          commit-message: |
            feat: update plugins

            ${{ steps.update.outputs.output }}
          delete-branch: true
          labels: dependencies
          reviewers: sonntag
          sign-commits: true
          title: "feat: update plugins"
