name: "Update flake"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Runs weekly on monday at 00:00

jobs:
  update-flake:
    name: Update flake
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Update flake.lock
        id: update-flake-lock
        uses: DeterminateSystems/update-flake-lock@v27
        with:
          commit-msg: "chore(deps): update flake.lock"
          pr-assignees: sonntag
          pr-labels: dependencies
          pr-reviewers: sonntag
          pr-title: "chore(deps): update flake.lock"
          # Wait for DeterminateSystems/update-flake-lock#200
          # sign-commits: true
      - name: Comment flake.lock changelog
        uses: mdarocha/comment-flake-lock-changelog@v0.9.2
        with:
          pull-request-number: ${{ steps.update-flake-lock.outputs.pull-request-number }}
